import 'room.dart';
import 'room_item.dart';

final List<Room> seedRooms = <Room>[
  Room(id: 1, name: "Room 1", presentItems: <RoomItem>[]),
  Room(id: 2, name: "Room 2", presentItems: <RoomItem>[]),
  Room(id: 3, name: "Room 2a", presentItems: <RoomItem>[]),
  Room(id: 4, name: "Room 3", presentItems: <RoomItem>[]),
  Room(id: 5, name: "Room 3a", presentItems: <RoomItem>[]),
  Room(id: 6, name: "Robot Room", presentItems: <RoomItem>[]),
  Room(id: 7, name: "Room 4", presentItems: <RoomItem>[]),
  Room(id: 8, name: "Room 5", presentItems: <RoomItem>[]),
  Room(id: 9, name: "Room 6", presentItems: <RoomItem>[]),
  Room(id: 10, name: "Room 7", presentItems: <RoomItem>[]),
  Room(id: 11, name: "Room 8", presentItems: <RoomItem>[]),
  Room(
    id: 12,
    name: "Vascular Suite",
    presentItems: <RoomItem>[],
  ),
  Room(id: 13, name: "Room 9", presentItems: <RoomItem>[]),
  Room(id: 14, name: "Room 10", presentItems: <RoomItem>[]),
  Room(id: 15, name: "Room 11", presentItems: <RoomItem>[]),
  Room(id: 16, name: "Room 12", presentItems: <RoomItem>[]),
  Room(id: 17, name: "Room 14", presentItems: <RoomItem>[]),
  Room(id: 18, name: "Room 15", presentItems: <RoomItem>[]),
  Room(id: 19, name: "Room 16", presentItems: <RoomItem>[]),
  Room(id: 20, name: "Room 17", presentItems: <RoomItem>[]),
  Room(id: 21, name: "Room 18", presentItems: <RoomItem>[]),
  Room(id: 22, name: "Room 19", presentItems: <RoomItem>[]),
  Room(id: 23, name: "Room 20", presentItems: <RoomItem>[]),
  Room(
    id: 24,
    name: "Neuro Interventional Radiology",
    presentItems: <RoomItem>[],
  ),
  Room(
    id: 25,
    name: "Cardiac Cath Lab",
    presentItems: <RoomItem>[],
  ),
  Room(
    id: 26,
    name: "Burn Surgery Suite",
    presentItems: <RoomItem>[],
  ),
];

// final List<RoomItem> seedItems = <RoomItem>[
//   RoomItem(id: 1, name: "ABG"),
//   RoomItem(id: 2, name: "14G"),
//   RoomItem(id: 3, name: "16G"),
//   RoomItem(id: 4, name: "18G"),
//   RoomItem(id: 5, name: "20G"),
//   RoomItem(id: 6, name: "22G"),
//   RoomItem(id: 7, name: "24G"),
//   RoomItem(id: 8, name: "25G"),
//   RoomItem(id: 9, name: "3cc"),
//   RoomItem(id: 10, name: "5cc"),
//   RoomItem(id: 11, name: "10cc"),
//   RoomItem(id: 12, name: "20cc"),
//   RoomItem(id: 13, name: "26cc"),
//   RoomItem(id: 14, name: "Art"),
//   RoomItem(id: 15, name: "Large TD"),
//   RoomItem(id: 16, name: "Small TD"),
//   RoomItem(id: 17, name: "Vamp"),
//   RoomItem(id: 18, name: "1L ISO"),
//   RoomItem(id: 19, name: "2L ISO"),
//   RoomItem(id: 20, name: "3L ISO"),
//   RoomItem(id: 21, name: "4L ISO"),
//   RoomItem(id: 22, name: "5L ISO"),
//   RoomItem(id: 23, name: "1L NS"),
//   RoomItem(id: 24, name: "2L NS"),
//   RoomItem(id: 25, name: "3L NS"),
//   RoomItem(id: 26, name: "4L NS"),
//   RoomItem(id: 27, name: "5L NS"),
//   RoomItem(id: 28, name: "500cc NS"),
//   RoomItem(id: 29, name: "2 500cc NS"),
//   RoomItem(id: 30, name: "250cc NS"),
//   RoomItem(id: 31, name: "50cc NS"),
//   RoomItem(id: 32, name: "100CC NS"),
//   RoomItem(id: 33, name: "Insulin Syringe"),
//   RoomItem(id: 34, name: "gravity"),
//   RoomItem(id: 35, name: "35"),
//   RoomItem(id: 36, name: "hotline"),
//   RoomItem(id: 37, name: "caresite"),
//   RoomItem(id: 38, name: "secondary"),
//   RoomItem(id: 39, name: "60"),
//   RoomItem(id: 40, name: "16 OG"),
//   RoomItem(id: 41, name: "18 OG"),
//   RoomItem(id: 42, name: "6 ET"),
//   RoomItem(id: 43, name: "6.5 ET"),
//   RoomItem(id: 44, name: "7 ET"),
//   RoomItem(id: 45, name: "7.5 ET"),
//   RoomItem(id: 46, name: "8 ET"),
//   RoomItem(id: 47, name: "8.5 ET"),
//   RoomItem(id: 48, name: "alcohol"),
//   RoomItem(id: 49, name: "flushes"),
//   RoomItem(id: 50, name: "heplocks"),
//   RoomItem(id: 51, name: "EKG"),
//   RoomItem(id: 52, name: "44"),
//   RoomItem(id: 53, name: "white pads"),
//   RoomItem(id: 54, name: "bio patches"),
//   RoomItem(id: 55, name: "sutures"),
//   RoomItem(id: 56, name: "MAC 3"),
//   RoomItem(id: 57, name: "MAC 4"),
//   RoomItem(id: 58, name: "Medium"),
//   RoomItem(id: 59, name: "Pediatric"),
//   RoomItem(id: 60, name: "Miller 2"),
//   RoomItem(id: 61, name: "Miller 3"),
//   RoomItem(id: 62, name: "tongue"),
//   RoomItem(id: 63, name: "stylets"),
//   RoomItem(id: 64, name: "Esophageal"),
//   RoomItem(id: 65, name: "Masks"),
//   RoomItem(id: 66, name: "Salters"),
//   RoomItem(id: 67, name: "Setup"),
//   RoomItem(id: 68, name: "Oxygen"),
//   RoomItem(id: 69, name: "Pump"),
//   RoomItem(id: 70, name: "Warmer"),
// ];
